#!/bin/sh

#set -x

#
# gettextize --copy --intl --force \
#

./clear && \
echo "-----------------------------------------------------------------------" && \
echo "cp..." && cp /usr/share/automake-1.9/mkinstalldirs config/ && \
echo "-----------------------------------------------------------------------" && \
echo "aclocal..." && aclocal -I m4 && \
echo "-----------------------------------------------------------------------" && \
echo "glib-gettextize..." && glib-gettextize -c -f && \
echo "-----------------------------------------------------------------------" && \
echo "autoheader..." && autoheader && \
echo "-----------------------------------------------------------------------" && \
echo "automake..." && automake --gnu --add-missing --copy --foreign; \
echo "-----------------------------------------------------------------------" && \
echo "autoconf..." && autoconf -f -Wall

